version: '3'

services:
  database:
    image: postgres:latest
    ports:
      - '5432:5432'
    container_name: 'nest-fastify-sls-db'
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest-fastify-sls-db
  adminer:
    image: adminer
    ports:
      - 8080:8080
    container_name: 'nest-fastify-adminer' 
    restart: always
volumes:
  pg-data: