service: nest-fastify-sls
frameworkVersion: '3'
plugins:
  - serverless-offline
  - serverless-typescript
package:
  patterns:
    - '!.git/**'
  excludeDevDependencies: true
provider:
  name: aws
  runtime: nodejs18.x

functions:
  swagger:
    handler: dist/lambda.handler
    events:
    - http:
        method: ANY
        path: /{proxy+}
        cors: true
  users:
    handler: dist/lambda.handler
    events:
    - http:
        method: GET
        path: /api/v1/users
        cors: true