service: nest-fastify-sls
frameworkVersion: '3'
plugins:
  - serverless-offline
  - serverless-typescript
provider:
  name: aws
  runtime: nodejs18.x

functions:
  main:
    handler: src/lambda.handler
    events:
    - http:
      method: ANY
      path: /{proxy+}

