service: nest-fastify-sls
frameworkVersion: '3'
plugins:
  - serverless-offline
  - serverless-typescript
package:
  patterns:
    - '!.git/**'
provider:
  name: aws
  region: us-east-1
  stage: ${sls:stage}
  runtime: nodejs18.x
  memorySize: 512
deploymentBucket:
  name: nest-fastify-sls-{sls:stage}
functions:
  auth:
    handler: dist/lambda.handler
    events:
    - http:
        method: GET
        path: /api/v1/login
        cors: true
  users:
    handler: dist/lambda.handler
    events:
    - http:
        method: GET
        path: /api/v1/users
        cors: true